# app/config/servers.yml
dev:
    host:          your-host.com
    user:          release
    identity_file:
        public_key: "~/.ssh/id_release.pub"
        private_key: "~/.ssh/id_release"
        password: "key-password"
    stage:         dev
    deploy_path:   "/var/www"
    branch:        dev